// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Meerkat.Security")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Paul Hatcher")]
[assembly: AssemblyVersionAttribute("3.1.0")]
[assembly: AssemblyFileVersionAttribute("3.1.0")]
[assembly: AssemblyInformationalVersionAttribute("3.1.0 bf52ce")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Meerkat.Security";
        internal const System.String AssemblyCopyright = "Copyright © 2016 Paul Hatcher";
        internal const System.String AssemblyVersion = "3.1.0";
        internal const System.String AssemblyFileVersion = "3.1.0";
        internal const System.String AssemblyInformationalVersion = "3.1.0 bf52ce";
    }
}
